### ISSUE TITLE
Adding a whole day event.

### ISSUE THREAD

**Issue by chrhol** [StarcounterApps/Calendar#1]
When I click on the whole day space for a day nothing happens. I have to click on some other time on that day and then click edit on the popup to be able to select whole day event.

Edit: tested this on chrome, both android and windows. No flags enabled though, not sure if that is needed or not?

**Comment by andwah** [comment]
It's nothing wrong with your chrome.

i have not yet added that "feature" thanks for reminding me :-)

**Comment by warpech** [comment]
Full day events are now present in the UI but not working correctly. This is tracked in https://github.com/StarcounterApps/Calendar/issues/41
