### ISSUE TITLE
Settings page redirects to `/` URL due to wrong user permissions

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Calendar#17]
If I start the following set of apps (built from GitHub develop branches):

```
staradmin start server
staradmin delete db default --force
call Launcher.bat
call SignIn.bat
call People.bat
  curl http://localhost:8080/signin/generateadminuser
call UserAdmin.bat
call Products.bat
call Cashier.bat
call Calendar.bat
```

Going to `/Launcher/settings` is not possible, becuase Calendar Settings partial page redirects to `/` URL due to some wrong user permissions.

**Comment by warpech** [comment]
Similar to https://github.com/StarcounterPrefabs/UserAdmin/issues/35, may be solved with the same solution.

**Comment by un-tone** [comment]
Created PRs https://github.com/StarcounterPrefabs/Calendar/pull/24 and https://github.com/StarcounterPrefabs/Calendar/pull/25

**Comment by andwah** [comment]
Clicking the "gear" icon, top right.

![image](https://cloud.githubusercontent.com/assets/2656996/23996745/e177754a-0a4e-11e7-9c55-52dc056f688e.png)

**Comment by un-tone** [comment]
Closing as done.

**Comment by warpech** [comment]
@un-tone what about the screenshot made by @andwah? Was that some bug or what?

**Comment by andwah** [comment]
> Was that some bug or what?

I used Latest Signin+Launcher+Calendar

**Comment by warpech** [comment]
By latest you mean latest from GitHub (what branch) or from Warehouse?

**Comment by un-tone** [comment]
I can't reproduce it. @andwah could you provide server logs with this error?

**Comment by andwah** [comment]
@un-tone Sorry. no logs available (i have deleted them). i will try to recreate the error

**Comment by andwah** [comment]
I pull the latest code and now i dont get this. (probably was using some old code)
