### ISSUE TITLE
Sign in form does not show up in standalone

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Calendar#21]
Sign in form does not show up in standalone

This is the same problem as in UserAdmin (https://github.com/StarcounterPrefabs/UserAdmin/issues/41), which was fixed in https://github.com/StarcounterPrefabs/UserAdmin/pull/53

### Steps to reproduce

1. Start Calendar
2. Start SignIn
3. Go to localhost:8080/calendar
4. Click "Settings"

### Expected result

You should see a sign in page.

### Actual result

You see a blank page.

##### Involved apps' version

StarcounterPrefabs/Calendar@42486153020e148d74fd61e5606159fb5c3d859f
StarcounterPrefabs/SignIn@3029c27df5c2d9567708d302206c1c9b1bdbf7d5
 
##### Browsers affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![2017-01-24 20_39_53-calendar](https://cloud.githubusercontent.com/assets/566463/22263599/4802ad18-e275-11e6-9742-cd711f79f8ed.png)

**Comment by warpech** [comment]
Requires clarification, because UserAdmin does not work at all with unauthenticated user. Calendar, however, has a UI for an unauthenticated user.

**Comment by un-tone** [comment]
This issue is related to https://github.com/StarcounterPrefabs/SignIn/issues/64

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/Calendar/pull/42

**Comment by un-tone** [comment]
Closing as done.
