### ISSUE TITLE
Map to SocietyObjects event

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Calendar#3]
Currently, the following line is commented out in Program.cs:

> Polyjuice.Map("/Calendar/events/@w", "/so/event/@w", null, null);

Let's try to restore the mapping to enable integration on URL OntologyMap level (such as having an Image for an Event, etc)

**Comment by chrhol** [comment]
I could not find this line you are pointing to so I guess it's been removed some time ago. Anyway, since I will be working on changing this in the calendar I will move this issue to me.

**Comment by warpech** [comment]
Unassigning @chrhol, because he is not currently working on it or will most probably not work on it anytime soon.

**Comment by warpech** [comment]
This won't be needed anymore
