### ISSUE TITLE
Get rid of the direct references to the Simplified/Smorgasbord.PropertyMetadata projects

### ISSUE THREAD

**Issue by un-tone** [StarcounterApps/Calendar#32]
The Calendar solution have direct references to the **Simplified** and **Smorgasbord.PropertyMetadata** projects.
In case with **Simplified** the Calendar project is using the public assembly. So it's enough to just remove Simplified from the solution.
In case with **Smorgasbord.PropertyMetadata** the Calendar project referenced to its project. I'm not sure what to do better. I see that for SignIn and UserAdmin, the components from **Smorgasbord.PropertyMetadata** was just copied with source files.

**Comment by Mackiovello** [comment]
Should be fixed with 77012f75265982362141741a2c0646d0958bb665. Please take a look and close if that's the case

**Comment by andwah** [comment]
`Smorgasbord.PropertyMetadata` exist in nuget, see https://www.nuget.org/packages/Smorgasbord.PropertyMetadata/

I think that should be used instead of the source files.

**Comment by un-tone** [comment]
@andwah agree.
@Mackiovello yes, it fixes with https://github.com/StarcounterApps/Calendar/commit/77012f75265982362141741a2c0646d0958bb665 .
Thanks!

**Comment by un-tone** [comment]
We can't use `Smorgasbord.PropertyMetadata` nuget-package since it causes the following issue https://github.com/StarcounterApps/Calendar/issues/34

**Comment by andwah** [comment]
I think `Smorgasbord.PropertyMetadata` version is outdated (it was compile with starcounter 2.2).
Should i  try to recompile it with latest Starcounter RC and update the nuget package?

**Comment by un-tone** [comment]
@andwah It would be helpful, sure

**Comment by andwah** [comment]
Just uploaded PropertyMetadata v1.0.0.2 to nuget,  lets hope is solves https://github.com/StarcounterApps/Calendar/commit/77012f75265982362141741a2c0646d0958bb665

**Comment by andwah** [comment]
if you dont see it in nuget this is why:
![image](https://cloud.githubusercontent.com/assets/2656996/24472821/69aa2052-14c7-11e7-86c2-9cef9b2e64f9.png)

**Comment by un-tone** [comment]
Thank you @andwah , it helps to resolve the issue.
