### ISSUE TITLE
Calendar picker looks corrupted after validation is show.

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Calendar#38]
### Steps to reproduce
1. Go to http://inside.starcounter.com/Calendar/render?view=agendaWeek&day=2017-11-13
2. Click at some date to add an event
3. fill the title
4. click "save"
5. open calendar picker

### Expected result
Upper line should be empty

### Actual result
It's full of down arrows.

##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot
![image](https://cloud.githubusercontent.com/assets/17435/24664948/354ea640-195c-11e7-8c63-d94b4aa42f68.png)

**Comment by warpech** [comment]
This happens when there is no calendar (`EventGroup`).

**Comment by PatrykSzwer** [comment]
I've created PR for that. #48

**Comment by PatrykSzwer** [comment]
Fixed in #48. Closing.
