### ISSUE TITLE
Add multi-day events

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Calendar#39]
### Steps to reproduce
It would be nice to be able to:
1. Go to monthly view http://inside.starcounter.com/Calendar/render?view=month&day=2017-11-06
2. Drag over few days

### Expected result
3. Fill the event details

### Actual result
nothing happens, I cannot find a way to add an event that spans over a day.

### Screenshot
![image](https://cloud.githubusercontent.com/assets/17435/24665144/c4b98ec6-195c-11e7-8101-e92e5ee7a02b.png)

![image](https://cloud.githubusercontent.com/assets/17435/24665119/b48ab5b6-195c-11e7-911b-03d11515e1eb.png)

**Comment by warpech** [comment]
This is needed to use Calendar app for vacation planning.

**Comment by PatrykSzwer** [comment]
I think first step to make that is to implement new functionality to sgb-fullcalendar element itself. Right now there is no feature like this, but, according to demo on fullcalendar repo ([selectable](https://github.com/Smorgasbord-Development/sgb-fullcalendar/blob/master/fullcalendar/demos/selectable.html)), it is possible to do.

**Comment by warpech** [comment]
@PatrykSzwer I've made you a collaborator at https://github.com/Smorgasbord-Development/sgb-fullcalendar

**Comment by PatrykSzwer** [comment]
After merging https://github.com/Smorgasbord-Development/sgb-fullcalendar/pull/2, this feature will be available.

**Comment by PatrykSzwer** [comment]
Smorgasbord-Development/sgb-fullcalendar#2 was merged, and all needed adjustments for correct working and bugfixes were made and merged in #57. Closing.

**Comment by tomalec** [comment]
@warpech Does inside.starcounter automatically fetches latest version of apps, or should it be manually pushed?

**Comment by warpech** [comment]
Apps must be manually installed there.
