### ISSUE TITLE
Full day events don't work correctly

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Calendar#41]
### Steps to reproduce

1. Go to http://inside.starcounter.com/Calendar/render
2. Click on some day to go to the view of that day
3. Click on top of the grid where it says "all-day"
4. Add an event

### Expected result

After saving, the event should be presented in the "all-day" section

### Actual result

After saving, the event is takes all hours during the day

##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

<img width="1419" alt="screen shot 2017-04-26 at 11 35 36" src="https://cloud.githubusercontent.com/assets/566463/25427954/7fc86aac-2a74-11e7-8b2c-44320c85ebc1.png">

**Comment by PatrykSzwer** [comment]
I actually couldn't reproduce this, nether on master or develop branch. Could You update deployed version and check again?

**Comment by warpech** [comment]
Seems fixed to me as well. Great!
