### ISSUE TITLE
Change styles to follow BEM convention

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Calendar#46]
Some of this styling, especially in [this](https://github.com/StarcounterApps/Calendar/blob/master/src/Calendar/wwwroot/Calendar/viewmodels/EventsPage.html) file, is not following BEM. 

Instructions to fix can be found in the [docs](https://docs.starcounter.io/guides/blending/avoiding-css-conflicts/).

**Comment by PatrykSzwer** [comment]
Done, closing.
