### ISSUE TITLE
Add comments in code that explain the usage of the Authorization library

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Calendar#69]
As discussed in https://github.com/StarcounterApps/Website/issues/123, add comments in code that explain the usage of the [Authorization](https://github.com/Starcounter/authorization) library in this app.

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/Calendar/pull/73

**Comment by un-tone** [comment]
Closing as done
