### ISSUE TITLE
"Permission denied" on SettingsPage

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Calendar#71]
### Steps to reproduce
1. Run https://github.com/StarcounterApps/Calendar/commit/dc86981c96370a6475b8400136a840bfcfdfe2c6 (current lastest version on develop)
2. Run SignIn (otherwise you'll get a message that requires you to sign in first)
3. Go to `http://localhost:8080/Calendar/settings`

This was discovered and commented in https://github.com/StarcounterApps/Calendar/pull/70 .
From what I understand, it worked before and now it doesn't.
README.md should be updated.

### Screenshot
<img width="519" alt="settings_calendar" src="https://user-images.githubusercontent.com/8951553/28826153-44a66a18-76c9-11e7-9abe-fe8e5d74ce08.png">

**Comment by warpech** [comment]
Thank you for submitting this. It is because Calendar app requires the user to be in a specific user group. Let's discuss here how it should be: https://github.com/Starcounter/Guidelines/issues/24

**Comment by PatrykSzwer** [comment]
Since after #81 was merged, for now on there is no need for Admin to be in specific Admin (calendars) group. Because It wasn't even bug at a first place I'll close this for now.
