### ISSUE TITLE
Create a filter for Calendar that filters out events for a specific participant.

### ISSUE THREAD

**Issue by chrhol** [StarcounterApps/Calendar#8]

**Comment by warpech** [comment]
Unassigning @chrhol, because he is not currently working on it or will most probably not work on it anytime soon.

**Comment by un-tone** [comment]
Created PRs https://github.com/StarcounterPrefabs/Simplified/pull/47 and https://github.com/StarcounterPrefabs/Calendar/pull/28

**Comment by un-tone** [comment]
Closing as done
