### ISSUE TITLE
Code revision and app recreation

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/Calendar#80]
Right now Calendar app is probably one of the most messy apps of our organisation. It has many lines of deprecated, unnecessary and in general bad code that has to be changed. Because of this entire app Is not properly optimized and part of the functionalities are not working or throwing exceptions from time to time. 

I will undertake the task to actually make something useful, working and readable from this app. I'm not sure how long is it going to take, and I'll need someone to review my changes. I'll create big pull requests for all those changes and It would be great If someone could take care of looking at those. 

I already know that I would like to ask @Joltrix for checking my changes in a context of timeline app (Since I'm removing/rearranging I can by mistake break integration with timeline app so quicker we found out that, It will be easier to fix it again)

**Comment by Mihaiii** [comment]
I agree that someone like @Joltrix would be the ideal reviewer in this case, but I can participate as a co-reviewer.

**Comment by PatrykSzwer** [comment]
Closing as done.
